### ISSUE TITLE
Tester can be much faster

### ISSUE THREAD

**Issue by qfox** [pensierinmusica/js-primes#1]
You can check division by 3 (summing all digits and checking `n mod 3 = 0`) and by 5 (comparing last digit to 0 and 5).

That's what I have on top of mind.

*_upd: *_ Also number must be a `6k±­1`. Either `(n+1)%2 = 0` and `sum of digits of ((n+1)/2) mod 3 = 0` or `(n-1)%2` and `sum of ...`.

**Comment by pensierinmusica** [comment]
Thanks for the input! This an old exercise I did a couple of years ago. If I happen to use this code in any real world task, I'll definitely think it through again and consider implementing your optimizations. Cheers  :)
